development:
  secret_key_base: "alamakota"
  information_service_url: "localhost/information"
  information_service_user: "scalarm"
  information_service_pass: "scalarm1024"
  redis_port: 6379
  redis_url: "redis://localhost:6379"
  redis_workers: 1
  sidekiq_username: "scalarm"
  sidekiq_password: "scalarm1024"
