default: &DEFAULT
  secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"

  information_service_url: "<%= ENV["INFORMATION_SERVICE_URL"] %>"
  information_service_user: "<%= ENV["INFORMATION_SERVICE_LOGIN"] %>"
  information_service_pass: "<%= ENV["INFORMATION_SERVICE_PASSWORD"] %>"
  
  redis_port: "<%= ENV["REDIS_PORT"] %>"
  redis_url: "<%= 'redis://' + ENV["REDIS_HOST"] + ':' + ENV["REDIS_PORT"] %>"
  redis_workers: 1
  
  sidekiq_username: "<%= ENV["SIDEKIQ_USERNAME"] %>"
  sidekiq_password: "<%= ENV["SIDEKIQ_PASSWORD"] %>"

  database:
    host: "<%= ENV['MONGO_ADDRESS'] %>"
    db_name: "<%= ENV['MONGO_DB_NAME'] %>"
    binaries_collection_name: 'simulation_files'
    pool_size: 2


development:
  <<: *DEFAULT

production:
  <<: *DEFAULT
