version: '2.0'
services:
  scalarm-redis:
    container_name: scalarm-redis
    image: redis
  scalarm-mongo:
    container_name: scalarm-mongo
    image: mongo:3.4.3
    command: --storageEngine wiredTiger
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOME/Scalarm/scalarm-db:/data/db 
  scalarm-experiment-manager:
    env_file:
      - $PWD/environment.env
    container_name: scalarm-experiment-manager
    image: dkrol3/scalarm:latest
    # entrypoint: sleep
    # command: infinity
    volumes:
      - $PWD/config/experiment_manager/config/puma.rb:/scalarm/config/puma.rb:ro
      - $PWD/config/experiment_manager/config/secrets.yml:/scalarm/config/secrets.yml:ro
      - $PWD/config/experiment_manager/config/mongoid.yml:/scalarm/config/mongoid.yml:ro
    links:
      - scalarm-mongo:mongo
      - scalarm-redis:redis
    ports:
      - ${EXPERIMENT_MANAGER_PORT}:${EXPERIMENT_MANAGER_PORT}
# Needed to work in Cyfronet
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
