development:
  secret_key_base: "alamakota"
  information_service_url: "192.168.98.100/information"
  information_service_user: "scalarm"
  information_service_pass: "scalarm1024"
  
  base_url: 'https://192.168.98.100'
  
  cors:
    allow_all_origins: false
    allowed_origins:
      - 'https://192.168.98.100'
