default: &DEFAULT
  secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"

  information_service_url: "<%= ENV["INFORMATION_SERVICE_URL"] %>"
  information_service_user: "<%= ENV["INFORMATION_SERVICE_LOGIN"] %>"
  information_service_pass: "<%= ENV["INFORMATION_SERVICE_PASSWORD"] %>"
  
  base_url: <%= 'https://localhost:' + ENV['DATA_EXPLORER_PORT'] %>

  # Leaving CORS configuration blank - we will allow all origins
  # (it's not very safe, but for development...)

  information_service_development: "<%= ENV['RAILS_ENV'] == 'development' ? 'true' : 'false' %>"

  database:
    host: "<%= ENV['MONGO_ADDRESS'] %>"
    db_name: "<%= ENV['MONGO_DB_NAME'] %>"
    binaries_collection_name: 'simulation_files'
    pool_size: 2

development:
  <<: *DEFAULT

production:
  <<: *DEFAULT
