development:
  secret_key_base: "alamakota"
  information_service_url: "localhost/information"
  information_service_user: "scalarm"
  information_service_pass: "scalarm1024"
  
  base_url: 'https://localhost'
  
  cors:
    allow_all_origins: false
    allowed_origins:
      - 'https://localhost'
      - 'https://https://149.156.11.4:10046'
